cronos/urls.py
# -*- coding: utf-8 -*-

from cronos.accounts.resources import UserResource
from cronos.posts.feeds import PostsFeed
from django.conf.urls.defaults import patterns, include, url
from django.conf import settings
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from tastypie.api import Api

handler500 = 'cronos.common.views.server_error'

urlpatterns = patterns('',
    (r'^$', 'cronos.accounts.views.accounts_index'),
    (r'^about/', 'cronos.common.views.about'),
    (r'^announcements/$', 'cronos.posts.views.posts', {'page': u'announcements', 'id': None}),
    (r'^api/', include(UserResource().urls)),
    (r'^blog/$', 'cronos.posts.views.posts', {'page': u'blog', 'id': None}),
    (r'^blog/feed/$', PostsFeed(), {'page': u'blog', 'username': None}),
    (r'^departments/(\d+)/$', 'cronos.posts.views.posts', {'page': u'department'}),
    (r'^dionysos/', 'cronos.teilar.views.dionysos'),
    (r'^eclass/', 'cronos.teilar.views.eclass'),
    (r'^announcements/(?P<username>\w+)/feed/$', PostsFeed(), {'page': u'announcements'}),
    (r'^library/', 'cronos.teilar.views.library'),
    (r'^login/', 'cronos.accounts.views.accounts_login'),
    (r'^logout/$', 'django.contrib.auth.views.logout', {'next_page': '/login'}),
    (r'^posts/(\d+)/$', 'cronos.posts.views.posts', {'page': u'post'}),
    (r'^refrigerators/', 'cronos.refrigerators.views.refrigerators'),
    (r'^settings/accounts/$', 'cronos.accounts.views.settings_accounts'),
    (r'^settings/announcements/$', 'cronos.accounts.views.settings_announcements'),
    (r'^settings/apikey/$', 'cronos.accounts.views.settings_apikey'),
    (r'^teachers/$', 'cronos.teilar.views.teachers'),
    (r'^teachers/(\d+)/$', 'cronos.posts.views.posts', {'page': u'teacher'}),
)

urlpatterns += staticfiles_urlpatterns()

user/models.py
# -*- coding: utf-8 -*-

from cronos.announcements.models import Id
from django.contrib.auth.models import User
from django.db import models

class UserProfile(models.Model):
    user = models.ForeignKey(User, unique = True)
    dionysos_username = models.CharField(max_length = 15, unique = True)
    dionysos_password = models.CharField(max_length = 30)
    eclass_username = models.CharField(max_length = 30, null = True, blank = True)
    eclass_password = models.CharField(max_length = 30, null = True, blank = True)
    eclass_lessons = models.TextField(null = True, blank = True)
    introduction_year = models.CharField(max_length = 5)
    registration_number = models.CharField(max_length = 8)
    school = models.CharField(max_length = 5)
    semester = models.CharField(max_length = 2)
    webmail_username = models.CharField(max_length = 30, null = True, blank = True)
    webmail_password = models.CharField(max_length = 30, null = True, blank = True)
    teacher_announcements = models.TextField(null = True, blank = True)
    other_announcements = models.TextField(null = True, blank = True)
    declaration = models.TextField(null = True, blank = True)
    grades = models.TextField(null = True, blank = True)
#    choice_field = models.ManyToManyField(Id)

    def __str__(self):
        return self.user.username
    
    class Admin:
        pass

cronos/teilar/forms.py
# -*- coding: utf-8 -*-

from django import forms

class LibraryForm(forms.Form):
    search = forms.CharField(label = 'Αναζήτηση', max_length = 100)

apps/dionysos/views.py
# -*- coding: utf-8 -*-

from apps.dionysos.forms import *
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.shortcuts import render_to_response
from django.template import RequestContext

@login_required
def dionysos(request):
    '''
    Retrieve the declaration and grades from the DB and print them
    '''

    '''
    Retrieve and print the declaration
    '''
    declaration_lessons = []
    if request.user.get_profile().declaration:
        declaration_full = request.user.get_profile().declaration.split(':')
        i = 0
        while i <= len(declaration_full):
            declaration_lessons.append(declaration_full[i:i+7])
            i += 7

    '''
    Retrieve and print the grades
    '''
    grades = []
    summary = None
    total = None
    '''
    if request.user.get_profile().grades:
        grades_full = request.user.get_profile().grades.split(',')
        length = len(grades_full)
        i = 0
        while i < length - 6:
            if grades_full[i][:7] == u'Εξάμηνο':
                grades.append([grades_full[i]])
                i += 1
            elif grades_full[i+5][:5] == 'total':
                grades.append([
                    str(grades_full[i]),
                    str(grades_full[i+1]),
                    #str(grades_full[i+2]),
                    grades_full[i+3],
                    #str(grades_full[i+4]),
                ])
                i += 6 
            else: 
                grades.append([
                    grades_full[i],
                    #str(grades_full[i+1]),
                    #str(grades_full[i+2]),
                    grades_full[i+3],
                    #str(grades_full[i+4]),
                    grades_full[i+5],
                    grades_full[i+6],
                ])
                i += 7
        total = [
            grades_full[i],
            grades_full[i+1],
            #str(grades_full[i+2]),
            grades_full[i+3],
            #str(grades_full[i+4]),
        ]'''
    return  render_to_response('dionysos.html', {
            'summary': summary,
            'declaration_lessons': declaration_lessons,
            'grades': grades,
            'total': total,
        }, context_instance = RequestContext(request))

apps/library/views.py
# -*- coding: utf-8 -*-

from apps.library.forms import LibraryForm
from apps.teilar.websites_login import teilar_login
from bs4 import BeautifulSoup
from django.shortcuts import render_to_response
from django.template import RequestContext

def library(request):
    '''
    Perform search in library.teilar.gr and print the results
    '''
    msg = None
    results = []
    if request.method == 'GET':
        form = LibraryForm(request.GET)
        if form.is_valid():
            url = 'http://hermes.lib.teilar.gr/ipac20/ipac.jsp?session=A26772NR74250.24315&menu=search&aspect=subtab22&npp=40&ipp=20&spp=20&profile=multbl--1&ri=&term=%s&index=.GEN&x=0&y=0&aspect=subtab22' % str(request.GET.get('search'))
            output = teilar_login(url)
            soup = BeautifulSoup(output).find_all('table')[24]
            temp_a_mediumboldanchor = soup.find_all('a', 'mediumBoldAnchor')
            temp_td = soup.find_all('td')
            i = 5
            for item in temp_a_mediumboldanchor:
                title = item.contents[0]
                '''
                The authors are in <i> tags. Take the list of them by
                taking a list of the contents of <i> tags, and then
                join the list with commas for prettier output
                '''
                authors = []
                tmp_authors = temp_td[i].find_all('i')
                for author in tmp_authors:
                    authors.append(author.contents[0].replace(',', '').strip())
                authors = ', '.join(authors)
                editor = temp_td[i+1].contents[0].contents[0].split(' : ')[1]
                city = temp_td[i+1].contents[0].contents[0].split(' : ')[0]
                i += 10
                results.append([title, authors, editor, city])
            if not results:
                msg = 'Δεν υπάρχουν αποτελέσματα'
    else:
        form = SearchForm()
    return render_to_response('library.html', {
            'form': form,
            'msg': msg,
            'results': results,
        }, context_instance = RequestContext(request))

apps/login/views.py
# -*- coding: utf-8 -*-

from apps import CronosError
from apps.login.forms import LoginForm
from django.contrib.auth import login, authenticate
from django.http import HttpResponseRedirect
from django.shortcuts import render_to_response
from django.template import RequestContext

def cronos_login(request):
    '''
    The login page (also the front page)
    '''
    msg = None
    form = None
    user = None
    if request.method == "POST":
        form = LoginForm(request.POST)
        if form.is_valid():
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']
        else:
            username = None
            password = None
        try:
            '''
            Perform authentication, if it retrieves a user object then
            it was successful. If it retrieves None then it failed to login
            '''
            user = authenticate(username = username, password = password, request = request)
            if not user:
                raise CronosError(u'Λάθος στοιχεία')
            if user.is_active:
                login(request, user)
                if not form.cleaned_data['remember']:
                    request.session.set_expiry(0)
                return HttpResponseRedirect('/')
        except CronosError as error:
            msg = error.value
    else:
        if request.user.is_authenticated():
            return HttpResponseRedirect('/')
        else:
            form = LoginForm()
    return render_to_response('login.html', {
       'msg': msg,
       'form': form,
        }, context_instance = RequestContext(request))

cronos/announcements/views.py
# -*- coding: utf-8 -*-

from cronos.announcements.models import Authors, Announcements
from cronos.announcements.forms import PostForm
from cronos.teilar.models import Departments as departments
from cronos.teilar.models import Teachers as teachers
from cronos.teilar.models import Websites as websites
from cronos.teilar.models import EclassLessons as eclasslessons
from django.contrib.auth.models import User
from django.contrib.contenttypes.models import ContentType
from django.http import HttpResponseRedirect
from django.shortcuts import render_to_response
from django.template import RequestContext

def get_creator(post, creator):
    '''
    Add creator's name, URL, mail and avatar in the post dict
    '''
    post.creator_url = creator.url.split('::')[0]
    if creator.email:
        post.creator_email = creator.email
    '''
    Get the avatar based on the url
    '''
    post.avatar = u'img/avatar_%s.png' % creator.url.split('/')[2]
    try:
        url = creator.url.split('/')[3]
        if url == u'tmimata':
            post.avatar = u'img/avatar_department.png'
        elif url.split('?')[0] == u'person.php':
            if url.split('=')[1] == u'323':
                post.avatar = u'img/avatar_calendar.png'
            elif url.split('=')[1] == u'324':
                post.avatar = u'img/avatar_news.png'
            else:
                post.avatar = u'img/avatar_teacher.png'
    except:
        pass
    try:
        url = creator.url.split('::')[1]
        if url == u'teilar_ann' or url == u'general':
            post.avatar = u'img/avatar_www.teilar.gr.png'
        else:
            post.avatar = u'img/avatar_%s.png' % url
    except:
        pass
    return post

def get_posts(request, id, title):
    login_required = True
    '''
    Prints posts
    '''
    posts = []
    following_authors = []
    following_meta_authors = []
    creators = []
    if title == u'Άρθρο':
        '''
        If the post ID is passed in the URL, only
        this post will be shown
        '''
        post = Announcements.objects.get(pk=id)
        '''
        Add creator's URL, mail and avatar in the post
        '''
        post = get_creator(post, post.creator.content_object)
        if creator.url == u'http://cronos.teilar.gr':
            login_required = False
        return [post]
    elif title == u'Ανακοινώσεις':
        '''
        The following list has ManyToMany fields from UserProfile. In order
        to get each one of the authors that are included there, we need to
        iterate first the following_meta_authors list, and then iterate each
        one of their contents.
        '''
        following_meta_authors = [
            request.user.get_profile().following_eclass_lessons,
            request.user.get_profile().following_teachers,
            request.user.get_profile().following_websites,
            request.user.get_profile().following_blogs,
        ]
        '''
        Add the school in the following authors as well
        '''
        following_authors.append(request.user.get_profile().school)
    elif title == u'Φοιτητές':
        following_meta_authors.append(request.user.get_profile().students)
    elif title == u'Blog':
        following_authors.append(websites.objects.get(url=u'http://cronos.teilar.gr'))
        login_required = False
    elif title == u'Τμήμα':
        following_authors.append(departments.objects.get(url__endswith = '=' + id))
    elif title == u'Καθηγητής':
        following_authors.append(teachers.objects.get(url__endswith = '=' + id))
    '''
    Get authors from the ManyToMany fields
    '''
    for list_of_authors in following_meta_authors:
        for author in list_of_authors.all():
            following_authors.append(author)
    '''
    Find the creators and put them all in a list, so we can retrieve
    all of their posts from a query
    '''
    for author in following_authors:
        author_type = ContentType.objects.get_for_model(author)
        creator = Authors.objects.get(content_type__pk = author_type.id, object_id = author.id)
        creators.append(creator)
    '''
    Get all the posts
    '''
    posts_q = Announcements.objects.filter(creator__in = creators).order_by('-pubdate')
    for post in posts_q:
        '''
        Add creator's URL, mail and avatar in the post
        '''
        post = get_creator(post, post.creator.content_object)
        '''
        Add the post in the list of the wanted posts
        '''
        posts.append(post)
    posts.append(login_required)
    return posts

def posts(request, id, title):
    login_required = True
    try:
        posts = get_posts(request, id, title)
        login_required = posts.pop()
    except:
        pass
    if not request.user.is_authenticated():
        if login_required:
            return HttpResponseRedirect('/login/?next=%s' % request.path)
    return render_to_response('posts.html', {
            'posts': posts,
            'title': title,
        }, context_instance = RequestContext(request))

cronos/common/views.py
from django.shortcuts import render_to_response
from django.template import RequestContext, loader
from django.http import HttpResponseServerError

def about(request):
    '''
    The About webpage
    '''
    return render_to_response('about.html', {},
        context_instance = RequestContext(request))

def server_error(request, template_name='500.html'):
    '''
    500 error handler.
    Override 500 error page, in order to pass STATIC_URL to Context
    '''
    t = loader.get_template(template_name)
    return HttpResponseServerError(t.render(
        RequestContext(request, {'request_path': request.path})))

cronos/refrigerators/views.py
# -*- coding: utf-8 -*-

from cronos.refrigerators.forms import *
from django.conf import settings
from django.contrib.auth.decorators import login_required
from django.shortcuts import render_to_response
from django.template import RequestContext
from cronos.refrigerators.forms import Classes


def refrigerators(request):
	forms = {}
	varDict = {}
	for i in Classes:
		forms[i().__class__.__name__] = i(request.POST)
	print "request.method  ===  ", request.method
	if request.method == 'POST':
		for i in forms:
			print forms[i].is_valid(), " || ", type(forms[i]), " || ", forms[i].errors, " || "
			if forms[i].is_valid():
				for j in forms[i].fields:
					forms[i].fields[j].__dict__['initial'] = 5.0
					if forms[i].fields[j].__class__.__name__ == "CharField":
						forms[i].fields[j].__dict__['initial'] = eval(request.POST.get(j))
					elif forms[i].fields[j].__class__.__name__ == "FloatField":
						forms[i].fields[j].__dict__['initial'] = float(request.POST.get(j))
						#print "\n\n\t FLOAT var ==", float(request.POST.get(j)), "\n\t initial value from request ==", forms[i].fields[j].__dict__['initial'], "\n\t VAR_NAME == ", j, "-.-"
					elif forms[i].fields[j].__class__.__name__ == "ChoiceField":
						print "\nChoiceField\n"
					else:
						print "\ninvalid formField \n"
		print "len(forms) === ", len(forms)
		for i in forms:
			formsname = ''
			for k in str(type(forms[i]))[27:]:
				if k.isdigit()>0 or k.isalpha()>0:
					formsname=formsname+k
				else:
					pass
			varDict[formsname] = forms[i]
		print "\n\tvarDictIF ===\n"
		print "\n\n form2.fields['sint_thermop2'].__dict__['initial'] = ", varDict['form2'].fields['sint_thermop2'].__dict__['initial'], "\n\n"
		print "\n\n evalEquations() = ", varDict['form2'].evalEquations()
	else:
		for i in forms:
			formsname = ''
			for k in str(type(forms[i]))[27:]:
				if k.isdigit()>0 or k.isalpha()>0:
					formsname=formsname+k
				else:
					pass
			varDict[formsname] = forms[i]
		print "\n\tvarDictELSE ===\n\n\n", varDict
	# 'XMLFILENAME' will be replaced by the urls./extensions(ex-refrigerators)
	# /UserSelectedURL(e.g. refiregerators)/.
	return render_to_response('refrigerators.html', varDict, context_instance = RequestContext(request))

cronos/teachers/views.py
# -*- coding: utf-8 -*- 

from cronos.announcements.models import Id
from django.shortcuts import render_to_response
from django.template import RequestContext

def teachers(request):
    teachers_list = []
    for item in Id.objects.filter(urlid__startswith = 'pid').order_by('name'):
        teachers_list.append([item.name, item.email, item.department])
    return render_to_response('teachers.html', {
            'teachers': teachers_list,
        }, context_instance = RequestContext(request))

cronos/templates/base.html
{% load staticfiles %}
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
    <head>
        <meta http-equiv="content-type" content="text/html; charset=UTF-8" />
        <title>{% block title %}{% endblock %}Cronos</title>
        <link rel="icon" href="{% static "img/logo.png" %}" type="image/x-icon">
        <link rel="stylesheet" href="{% static "css/reset.css" %}">
        <link rel="stylesheet" href="{% static "css/style.css" %}">
        {% block more %}{% endblock %}
        <script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.4.2/jquery.min.js"></script>
        <script type="text/javascript" src="{% static "js/sidebar.js" %}"></script>
        {% block extra_css %}{% endblock %}
        {% block extra_js_top %}{% endblock %}
    </head>
    <body>
        <div id="container">
            <div id="header">
                <a href="/"><h1>CRONOS</h1></a>
                <div id="sidebar">
                    <ul id="navigation">
                        <li><a href="/">&raquo;&emsp;Αρχική</a></li>
                        {% if user.is_authenticated %}
                            <li><a href="/announcements/">&raquo;&emsp;Ανακοινώσεις</a></li>
                            <li><a href="/dionysos/">&raquo;&emsp;Στοιχεία Γραμματείας</a></li>
                            {% if user.get_profile.eclass_username %}
                                <li><a href="/eclass/">&raquo;&emsp;E-class</a></li>
                            {% endif %}
                            {% if user.get_profile.webmail_username %}
                                <li><a href="/webmail/">&raquo;&emsp;E-mail</a></li>
                            {% endif %}
                        {% endif %}
                        <li><a href="/library/">&raquo;&emsp;Αναζήτηση Βιβλιοθήκης</a></li>
                        <li><a href="/teachers/">&raquo;&emsp;Λίστα Καθηγητών</a></li>
                        <li class="sidebar_head"><a>&raquo;&emsp;Extensions</a></li>
                        <div class="sidebar_body">
                            <li><a href="/refrigerators/">&raquo;&emsp;Ψυκτικά Φορτία</a></li>
                        </div>
                        <li><a href="/blog/">&raquo;&emsp;Blog</a></li>
                        {% if user.is_authenticated %}
                            <li class="sidebar_head"><a>&raquo;&emsp;Ρυθμίσεις</a></li>
                            <div class="sidebar_body">
                                <li><a href="/settings/accounts/">&raquo;&emsp;Ρυθμίσεις Λογαριασμών</a></li>
                                <li><a href="/settings/announcements/">&raquo;&emsp;Επιλογή ανακοινώσεων</a></li>
                                <li><a href="/settings/apikey/">&raquo;&emsp;API key</a></li>
                            </div>
                        {% endif %}
                        <li><a href="/about/">&raquo;&emsp;Σχετικά</a></li>
                    </ul>
                </div>
            </div>
            {% if user.is_authenticated %}
                <div id="profile">
                    <p>{{user.first_name}} {{user.last_name}}&emsp;&mdash;&emsp;{{user.get_profile.registration_number}}</p>
                    <a class="button" href="/logout/">Αποσύνδεση</a>
                </div>
            {% endif %}
            <div id="content">
            <div id="notifications">
                {% if notification.info %}
                    <p class="infobox">{{ notification.info|safe }}</p>
                {% elif notification.error %}
                    <p class="errorbox">{{ notification.error|safe }}</p>
                {% elif notification.success %}
                    <p class="successbox">{{ notification.success|safe }}</p>
                {% endif %}
                {% block notifications %}{% endblock %}
            </div>
                {% block content %}{% endblock %}
            </div>
        </div>
        {% block extra_js_bottom %}{% endblock %}
    </body>
</html>

cronos/templates/intro.html
{% load staticfiles %}
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
    <head>
        <meta http-equiv="content-type" content="text/html; charset=UTF-8" />
        <title>{% block title %}{% endblock %}Cronos</title>
        <link rel="icon" href="{% static "img/logo.png" %}" type="image/x-icon">
        <link rel="stylesheet" href="{% static "css/reset.css" %}">
        <link rel="stylesheet" href="{% static "css/style_intro.css" %}">
        <script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.4.2/jquery.min.js"></script>
        <script type="text/javascript">
        </script>
    </head>
    <body>
        <div id="container">
            <h1>CRONOS</h1>
            {% block content %}{% endblock %}
        </div>
    </body>
</html>

cronos/templates/library.html
{% extends "base.html" %}

{% block title %}
Βιβλιοθήκη | 
{% endblock %}
{% block content %}
    <div class="entry">
        <h3>Αναζήτηση</h3>
        <form action="/library/" method="get">
            {% for field in form %}
            {{ field.label.tag }}{{ field }}
            {% endfor %}
            <input type="submit" value="Αναζήτηση" />
        </form>
    </div>
    {% if msg %}
    <div id="notifications">
        <p>{{msg}}</p>
    </div>
    {% endif %}
    {% if results %}
        <div class="entry">
            <h3>Αποτελέσματα</h3>
            <ul>
            {% for i in results %}
                <li>
                {% for j in i %}
                    {% cycle '<b>' '</b><br/>&nbsp;&nbsp;&nbsp;&nbsp;<i>Συγγραφέας:</i> ' '</i><br />&nbsp;&nbsp;&nbsp;&nbsp;<i>Εκδοτικός Οίκος:</i> ' ', ' %}{{j|safe}}
                {% endfor %}
                </li>
            {% endfor %}
            </ul>
        </div>
    {% endif %}
{% endblock %}

cronos/templates/preferences.html
{% extends "base.html" %}

{% block title %}
    Ρυθμίσεις χρήστη {{user}} | 
{% endblock %}

{% block extra_js_top %}
    <script type="text/javascript" src="{{MEDIA_URL}}js/multibox.js"></script>
{% endblock %}

{% block content %}
    {% if msg %}
        <div id="notifications">
            <p>{{ msg }}</p>
        </div>
    {% endif %}
    <div class="entry" id="teilar">
        <h3>Λογαριασμοί υπηρεσιών ΤΕΙ Λάρισας</h3>
        <p>Σε περίπτωση που αλλάξατε το όνομα χρήστη ή τον κωδικό πρόσβασης για
        κάποια από τις ακόλουθες υπηρεσίες του ΤΕΙ Λάρισας, ή εαν θέλετε να
        προσθέσετε κάποια από αυτές στο λογαριασμό σας στο Cronos, συμπληρώστε τα νέα
        στοιχεία στην κατάλληλη φόρμα</p>
        <table>
            <tr>
                <th><i><a href="http://e-class.teilar.gr">e-class.teilar.gr</a>: </i>
                    {% if user.get_profile.eclass_username %}
                        {{ user.get_profile.eclass_username }}
                    {% else %}
                        ----
                    {% endif %}
                </th>
                <th><i><a href="http://myweb.teilar.gr">myweb.teilar.gr</a>: </i>
                    {% if user.get_profile.webmail_username %}
                        {{ user.get_profile.webmail_username }}
                    {% else %}
                        ----
                    {% endif %}
                </th>
            </tr>
            <tr>
               <td>
                    <form action="." method="POST" align="center">
                        {% for field in eclass_credentials_form %}
                            {{ field }}<br />
                        {% endfor %}
                        <input class="button" type="submit" value=
                        {% if user.get_profile.eclass_username %}
                            "Ανανέωση"
                        {% else %}
                            "Προσθήκη"
                        {% endif %}
                        />
                    </form>
                </td>
                <td>
                    <form action="." method="POST" align="center">
                        {% for field in webmail_form %}
                            {{ field }}<br />
                        {% endfor %}
                        <input class="button" type="submit" value=
                        {% if user.get_profile.webmail_username %}
                            "Ανανέωση"
                        {% else %}
                            "Προσθήκη"
                        {% endif %}
                        />
                    </form>
                </td>
            </tr>
        </table>
    </div>

    <div class="entry" id="other">
        <h3>Άλλα Στοιχεία</h3>
        <table>
            <tr>
                <th><a href="/dionysos/#declaration">Δήλωση Μαθημάτων</a></th>
                <th><a href="/dionysos/#grades">Βαθμολογία</a></th>
                {% if user.get_profile.eclass_username %}
                    <th><a href="/eclass">Μαθήματα E-class</a></th>
                {% endif %}
            </tr>
            <tr>
                <td>
                    <form action="." method="POST" align="center">
                        {% for field in declaration_form %}
                            {{ field }}
                        {% endfor %}
                        <input class="button" type="submit" value="Ανανέωση" />
                    </form>
                </td>
                <td>
                    <form action="." method="POST" align="center">
                        {% for field in grades_form %}
                            {{ field }}
                        {% endfor %}
                        <input class="button" type="submit" value="Ανανέωση" />
                    </form>
                </td>
                <td>
                    {% if user.get_profile.eclass_username %}
                    <form action="." method="POST" align="center">
                        {% for field in eclass_lessons_form %}
                            {{ field }}
                        {% endfor %}
                        <input class="button" type="submit" value="Ανανέωση" />
                    </form>
                    {% endif %}
                </td>
            </tr>
        </table>
    </div>

    <div class="entry" id="theacher">
        <h3>Ανακοινώσεις Καθηγητών</h3>
        <div>
            <form action="." method="POST" id="teacherann">
                <select multiple="multiple" name="teacher_announcements" id="id_teacher_announcements">
                    {% for i in teacher_announcements_all %}
                        {% for j in i %}
                            {% if forloop.counter0 = 0 %}
                                <option value="{{j|safe}}">
                            {% else %}
                                {{j|safe}}</option>
                            {% endif %}
                        {% endfor %}
                    {% endfor %}
                </select>
                <select multiple="multiple" name="teacherann_selected" id="teacherann_selected">
                    {% for i in teacher_announcements_selected %}
                        {% for j in i %}
                            {% if forloop.counter0 = 0 %}
                                <option value="{{j|safe}}">
                            {% else %}
                                {{j|safe}}</option>
                            {% endif %}
                        {% endfor %}
                    {% endfor %}
                </select>
                <div id="add1pl"><a href="#" id="add1">Προσθήκη &gt;&gt;</a></div>
                <div id="remove1pl"><a href="#" id="remove1">&lt;&lt; Αφαίρεση</a></div>
                <br /><br /><br />
                <input class="button" type="submit" value="Ανανέωση" />
            </form>
            <form action="." method="POST">
                <input class="button" type="submit" value="Διαγραφή Όλων" />
            </form>
        </div>
    </div>

    <div class="entry" id="otherann">
        <h3>Άλλες Ανακοινώσεις</h3>
        <div>
            <form action="." method="POST" id="otherann">
            <select multiple="multiple" name="other_announcements" id="id_other_announcements">
                {% for i in other_announcements_all %}
                    {% for j in i %}
                        {% if forloop.counter0 = 0 %}
                            <option value="{{j|safe}}">
                        {% else %}
                            {{j|safe}}</option>
                        {% endif %}
                    {% endfor %}
                {% endfor %}
            </select>
                <select multiple="multiple" name="otherann_selected" id="otherann_selected">
                    {% for i in other_announcements_selected %}
                        {% for j in i %}
                            {% if forloop.counter0 = 0 %}
                                <option value="{{j|safe}}">
                            {% else %}
                                {{j|safe}}</option>
                            {% endif %}
                        {% endfor %}
                    {% endfor %}
                </select>
                <div id="add2pl"><a href="#" id="add2">Προσθήκη &gt;&gt;</a></div>
                <div id="remove2pl"><a href="#" id="remove2">&lt;&lt; Αφαίρεση</a></div>
                <br /><br /><br />
                <input class="button" type="submit" value="Ανανέωση" name="update" />
            </form>
            <form action="." method="POST">
                <input class="button" type="submit" value="Διαγραφή Όλων" name="delete2" />
            </form>
        </div>
    </div>
{% endblock %}